using MediatR;
using Res = MilesCarRental.Domain.Availability.Response;

namespace MilesCarRental.Application.Availability.Queries.GetAvailability
{
    /// <summary>
    /// Query to request real availability using a quickSearch token.
    /// </summary>
    /// <param name="QuickSearch">Opaque token generated by the website to reproduce a search.</param>
    public sealed record GetAvailabilityQuery(string QuickSearch) : IRequest<Res.Rootobject>;
}

